background {
    monitor =
    path = /usr/share/wallpapers/kafy/contents/images/1920x1080.png
    blur_passes = 2
    blur_size = 7
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffff)
    font_size = 56
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.18
    font_color = rgba(ffffffff)
    inner_color = rgba(20202ad0)
    outer_color = rgba(818cf8ff)
    fade_on_empty = false
    placeholder_text = Enter password
    position = 0, -30
    halign = center
    valign = center
}
