#!/bin/sh
set -eu

has_lb_option() {
  lb config --help 2>&1 | grep -q -- "$1"
}

set -- noauto \
  --architectures amd64 \
  --mode debian \
  --distribution bookworm \
  --archive-areas "main contrib non-free non-free-firmware" \
  --parent-mirror-bootstrap "http://deb.debian.org/debian" \
  --parent-mirror-chroot "http://deb.debian.org/debian" \
  --parent-mirror-binary "http://deb.debian.org/debian" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --parent-mirror-chroot-security "http://deb.debian.org/debian-security" \
  --parent-mirror-binary-security "http://deb.debian.org/debian-security" \
  --mirror-chroot-security "http://deb.debian.org/debian-security" \
  --mirror-binary-security "http://deb.debian.org/debian-security" \
  --binary-image iso-hybrid \
  --debian-installer false \
  --firmware-binary false \
  --firmware-chroot false \
  --iso-application "Kafy OS" \
  --iso-publisher "Kafy Project" \
  --iso-volume "KAFY_OS" \
  --linux-packages "linux-image" \
  --linux-flavours "amd64" \
  --memtest none

if has_lb_option "--security"; then
  set -- "$@" --security false
fi

if has_lb_option "--bootloaders"; then
  set -- "$@" --bootloaders "syslinux,grub-efi"
elif has_lb_option "--bootloader"; then
  set -- "$@" --bootloader syslinux
fi

if has_lb_option "--image-name"; then
  set -- "$@" --image-name kafy-os
fi

lb config "$@"
